//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerGamesLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComputerGame
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int YearPublished { get; set; }
        public int Price { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
