//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerGamesLibrary.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserComputerGame
    {
        public int ID { get; set; }

        [Required]
        [MinLength(3, ErrorMessage ="Title must be greater than 3 characters")]
        [MaxLength(100, ErrorMessage ="Title must be less than 100 characters")]
        public string Title { get; set; }

        [Required]
        [MinLength(3, ErrorMessage ="Genre must be greater than 3 characters")]
        [MaxLength(50, ErrorMessage ="Genre must be less than 50 characters")]
        public string Genre { get; set; }

        [Required]
        [Display(Name ="Year Published")]
        [RegularExpression(@"^(\d{4})$", ErrorMessage = "Enter a valid 4 digit Year")]
        public int YearPublished { get; set; }

        [Required]
        [Display(Name = "Price (£)")]
        [Column(TypeName ="decimal(18,2)")]
        public decimal Price { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
