//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerGamesLibrary.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserComputerGame
    {
        public int ID { get; set; }

        [Required]
        [MinLength(Constants.MIN_STRING_LENGTH, ErrorMessage = "Title must be 3 characters or more")]
        [MaxLength(Constants.MAX_NAME_LENGTH, ErrorMessage ="Title must be 100 characters or less")]
        public string Title { get; set; }

        [Required]
        [MinLength(Constants.MIN_STRING_LENGTH, ErrorMessage ="Genre must be 3 characters or more")]
        [MaxLength(Constants.MAX_GENRE_LENGTH, ErrorMessage ="Genre must 50 characters or less")]
        public string Genre { get; set; }

        [Required]
        [Display(Name ="Year Published")]
        [Range(0, Constants.UPPER_YEAR_LIMIT, ErrorMessage ="Year cannot be negative or greater than 4 digits")]
        [RegularExpression(@"^(\d{4})$", ErrorMessage = "Enter a valid 4 digit Year")]
        public int YearPublished { get; set; }

        [Required]
        [Display(Name = "Price (£)")]
        [Range(0, Constants.MAX_PRICE, ErrorMessage = "Price cannot be negative or greater than 18 digits")]
        [Column(TypeName ="decimal(18,2)")]
        public decimal Price { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
